version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: laravel-php
    volumes:
      - ./app:/usr/share/nginx/html:rw

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8085:80"
    volumes:
      - ./app:/usr/share/nginx/html:rw
    depends_on:
      - php
